# spring:
#   application:
#     name: authentication

#   cloud:
#     gateway:
#       routes:
#         # - id: service1
#         #   uri: http://localhost:8081
#         #   predicates:
#         #     - Path=/service1/**
#         #   filters:
#         #     - StripPrefix=1
#         - id: messages
#           uri: http://localhost:8082
#           predicates:
#             - Path=/messages/**
#           filters:
#             - StripPrefix=1

#   datasource:
#     url: jdbc:postgresql://localhost:5432/authentication
#     username: postgres
#     password: postgres
#     driver-class-name: org.postgresql.Driver

#   jpa:
#     properties:
#       hibernate:
#         show_sql: true
#         format_sql: true
#         type: trace
#     open-in-view: false
#     hibernate:
#       ddl-auto: update

#   data:
#     redis:
#       host: localhost
#       port: 6378

#   devtools:
#     livereload:
#       port: 35730
#       enabled: false

# server:
#   port: 8085

# logging:
#   level:
#     root: INFO
#   include-application-name: false
#   pattern:
#     console: '\u001b[38;5;0m%d{hh:mm:ss} \u001b[31;1m%level \u001b[33m%file::%L %n \u001b[38;5;0m --- \u001b[35m %m \u001b[0m %n'

# security:
#   ACCESS_SECRET: MY_SECRET_ACC
#   ACCESS_LIFETIME: 600000
#   REFRESH_SECRET: MY_SECRET_REF
#   REFRESH_LIFETIME: 3600000
